### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by afwolfe** [juliamertz/linux-fallout4-downgrader#1]
Hello, thank you for automating the Fallout 4 downgrade on Linux!
I would like to build on top of this script to automate the Fallout London install process on Linux, but realized there is no LICENSE associated with this repository.

Would you consider adding an open-source license to this repository so that others like myself can know how we are permitted to use it?

The GitHub documentation provides some instructions here: [Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

Thank you!

**Comment by juliamertz** [comment]
Sure, I've added a GPLv3 license. Let me know when you get it working, I'd like to try out Fallout London myself sometime!

**Comment by afwolfe** [comment]
Great thank you so much!
It's experimental, but it worked for me. I've been trying to add more validation and automation to it: [afwolfe/fallout-london-linux-installer](https://github.com/afwolfe/fallout-london-linux-installer)

I hope to eventually cleanup the modifications I made to the downgrader to allow a non-interactive install and upstream the changes.
